name: Build-vuOS

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  buildvu:
    # Name the Job
    name: Build vuOS
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get dependencies
        run: sudo apt update && sudo apt install build-essential mtools nasm xorriso grub-pc-bin -y
          
      - name: Build vuOS
        run: mkdir -p ./iso/boot/grub && nasm -f elf32 Loader.s -o Loader.o && gcc -c Kernel.c -m32 -nostdlib -nostdinc -ffixed-ecx -fno-builtin -fno-stack-protector -nostartfiles -nodefaultlibs -W && ld -T Link.ld -melf_i386 Loader.o Kernel.o  -o ./iso/boot/vuos-seatray.elf
          
      - name: Make disk image
        run: cp grub.cfg ./iso/boot/grub && ls ./iso/boot && grub-mkimage -o vuos-i686.iso -O i386-pc -C xz -p /boot/grub iso/
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
         name: vuos-i686.iso
         path: ./vuos-i686.iso
