name: Lint Code
on: push
jobs:
  lint:
    name: Lint Code Base
    uses: github/super-linter@v3
    runs-on: macos-latest
    env:
      VALIDATE_ALL_CODEBASE: false
      DEFAULT_BRANCH: master
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
